name: Outside API Deployment

on:
  push:
    branches:
      - master # Deploy when pushing to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "VITE_BASE_API_URL=${{ secrets.ENV }}" > .env

      - name: Deploy With FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/api.e-learn.name.ng/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**

      - name: Install dependencies and run migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 21098
          script: |
            cd public_html/api.e-learn.name.ng
            composer install
            composer dump-autoload
            php artisan migrate --force
